name: Test and Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: bundle install
      - name: Run RSpec tests
        run: bundle exec rspec

  cross-build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cross-Build and Push Docker Image
        run: |
          docker buildx build --push \
            --platform linux/arm64,linux/amd64 \
            --tag ghcr.io/glombek/ical-filter-proxy:latest .
